require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/*"
  NewCops: enable

Layout/LineLength:
  Max: 130
  Exclude:
    - "Rakefile"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

Metrics/AbcSize:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 8

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 200

Metrics/BlockLength:
  Max: 50
  Exclude:
    - "spec/**/*"

Metrics/BlockNesting:
  Max: 5

Metrics/ClassLength:
  Max: 120

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false
